# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Holomouseio_Template' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  rn_path = '../node_modules/react-native'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [ 'CxxBridge', 'RCTImage' ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'Firebase/Core', "5.20.2"
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # target 'Holomouseio_TemplateTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

target 'Holomouseio_Template-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Holomouseio_Template-tvOS

  target 'Holomouseio_Template-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
