# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '{{name}}' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'React', :path => '../node_modules/react-native', :subspecs => [ 'RCTImage' ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target '{{name}}Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target '{{name}}-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for {{name}}-tvOS

  target '{{name}}-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
